[package]
name = "coreoverlay-engine"
authors = ["Shota Shimazu <hornet.live.mf@gmail.com>"]
description = "Core engine for CoreOverlay"
repository = "https://github.com/shotastage/CoreOverlay"
version = "0.1.1"
edition = "2021"
exclude=["/src-swift", "/co-desktop", "/co-cli",, "/src-go", "*.swift"]
license = "MIT"
publish = false


[lib]
name = "coreoverlayengine"
crate-type = [ "staticlib" ]
path = "rust-src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasmer = "4.0.0"
futures = "0.3.25"
anyhow = "1.0"
async-ffi = "0.4.0"
tokio = { version = "1.24.0", features = ["full"] }
safer-ffi = "0.0.10"
sha1 = "0.10.5"
swift-bridge = "0.1"
libc = "0.2"


[build-dependencies]
build-deps = "0.1.4"
anyhow = "1.0"
glob = "0.3"
rustc_version = "0.4"
swift-bridge-build = "0.1"
cbindgen = "0.24.3"


[dev-dependencies]
anyhow = "1.0"
criterion = "0.3"
lazy_static = "1.4"
serial_test = "0.5"
tempfile = "3.1"
async-std = { version = "1.11.0", features = ["attributes"] }
async-executor = "1.4.1"
