[package]
name = "coreoverlay-engine"
authors = ["Shota Shimazu <hornet.live.mf@gmail.com>"]
repository = "https://github.com/shotastage/CoreOverlay"
version = "0.1.0"
edition = "2021"


[lib]
name = "coreoverlayengine"
crate-type = [ "staticlib" ]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasmer = "3.0"
futures = "0.3.25"
anyhow = "1.0"
async-ffi = "0.4.0"
tokio = "1.24.0"
safer-ffi = "0.0.10"
sha1 = "0.10.5"

[dependencies.libp2p]
version = "0.50.0"
features = [
    "async-std",
    "autonat",
    "dcutr",
    "deflate",
    "dns",
    "ecdsa",
    "floodsub",
    "gossipsub",
    "identify",
    "kad",
    "mdns",
    "metrics",
    "mplex",
    "noise",
    "ping",
    "plaintext",
    "pnet",
    "quic",
    "macros",
    "relay",
    "rendezvous",
    "request-response",
    "secp256k1",
    "serde",
    "tcp",
    "tls",
    "tokio",
    "uds",
    "webrtc",
    "websocket",
    "yamux",
]

[dependencies.async-std]
version = "1.11.0"
features = ["attributes"]

[build-dependencies]
build-deps = "0.1.4"
anyhow = "1.0"
glob = "0.3"
rustc_version = "0.4"

[dev-dependencies]
anyhow = "1.0"
criterion = "0.3"
lazy_static = "1.4"
serial_test = "0.5"
tempfile = "3.1"
async-std = { version = "1.11.0", features = ["attributes"] }
async-executor = "1.4.1"
