[package]
name = "coreoverlay-engine"
authors = ["Shota Shimazu <hornet.live.mf@gmail.com>"]
repository = "https://github.com/shotastage/CoreOverlay"
version = "0.1.0"
edition = "2021"


[lib]
name = "coreoverlayengine"
crate-type = [ "staticlib" ]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasmer = "3.0"
anyhow = "1.0"
libp2p = "0.50.0"

[build-dependencies]
build-deps = "0.1.4"
anyhow = "1.0"
glob = "0.3"
rustc_version = "0.4"

[dev-dependencies]
anyhow = "1.0"
criterion = "0.3"
lazy_static = "1.4"
serial_test = "0.5"
tempfile = "3.1"
