[package]
name = "coreoverlay-engine"
authors = ["Shota Shimazu <hornet.live.mf@gmail.com>"]
description = "Core engine for CoreOverlay"
repository = "https://github.com/shotastage/CoreOverlay"
version = "0.1.1"
edition = "2021"
exclude=["/src-swift", "/co-desktop", "*.swift"]
license = "MIT"
publish = false


[lib]
name = "coreoverlayengine"
crate-type = [ "staticlib" ]
path = "src-rust/lib.rs"

[[bin]]
name = "coreoverlay"
path = "src-rust/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasmer = "5.0"
futures = "0.3"
anyhow = "1.0"
tokio = { version = "1.43", features = ["full"] }
sha1 = "0.10"
swift-bridge = "0.1"
libc = "0.2"
colored = "3.0"
hex = "0.4"
clap = { version = "4.5", features = ["derive"] }
overlaystd = { path = "lib/overlaystd" }
algs = { path = "lib/algs" }
codb = { path = "lib/codb" }
protocol = { path = "lib/protocol" }
ovlyvm = { path = "lib/ovlyvm" }
ovlypkg = { path = "lib/ovlypkg" }
replicafs = { path = "lib/replicafs" }

[workspace]
members = [
    "lib/algs",
    "lib/codb",
    "lib/overlaystd",
    "lib/protocol",
    "lib/ovlyvm",
    "lib/ovlypkg",
    "lib/devhelper",
    "lib/replicafs",
]

[workspace.package]
authors = ["Shota Shimazu <hornet.live.mf@gmail.com>"]
edition = "2021"
homepage = "https://mgq.app/"
license = "MIT"
repository = "https://github.com/shotastage/CoreOverlay"
version = "0.1.1"

[build-dependencies]
build-deps = "0.1"
anyhow = "1.0"
glob = "0.3"
rustc_version = "0.4"
swift-bridge-build = "0.1"
cbindgen = "0.24"

[dev-dependencies]
anyhow = "1.0"
criterion = "0.3"
lazy_static = "1.4"
serial_test = "0.5"
tempfile = "3.1"
async-std = { version = "1.11", features = ["attributes"] }
async-executor = "1.4"
