[package]
name = "replicrypt"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
sha1 = "0.10.0"

[[bin]]
name = "replicrypt"
path = "src/main.rs"
