version: 2.1
jobs:
  build:
    docker:
      - image: rust:latest
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - restore_cache:
          name: Restore Rust packaging compiled cache
          keys:
            - v1-dependencies-{{ checksum "Cargo.toml" }}-{{ checksum "Cargo.lock" }}
      - run: apt-get update && apt-get install -y protobuf-compiler
      - run: curl -sSf https://sh.rustup.rs | sh -s -- -y
      - run: rustup component add rustfmt
      - run: cargo install grpcio-compiler
      - run: cargo build --release
      - store_artifacts:
          path: ./target/release/
      - save_cache:
          name: save
          paths:
            - ./target/
            - ~/.cargo/
          key: v1-dependencies-{{ checksum "Cargo.toml" }}-{{ checksum "Cargo.lock" }}
